# Generated by Django 6.1 on 2026-08-13 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('followers', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('HIP_HOP', 'Hip Hop'), ('RAP', 'Rap'), ('RNB', 'R&B'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('COUNTRY', 'Country'), ('FOLK', 'Folk'), ('CLASSICAL', 'Classical'), ('ELECTRONIC', 'Electronic'), ('HOUSE', 'House'), ('TECHNO', 'Techno'), ('TRANCE', 'Trance'), ('DUBSTEP', 'Dubstep'), ('DRUM_AND_BASS', 'Drum and Bass'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('SKA', 'Ska'), ('PUNK', 'Punk'), ('METAL', 'Metal'), ('HEAVY_METAL', 'Heavy Metal'), ('DEATH_METAL', 'Death Metal'), ('METALCORE', 'Metalcore'), ('ALTERNATIVE', 'Alternative'), ('INDIE', 'Indie'), ('INDIE_ROCK', 'Indie Rock'), ('INDIE_POP', 'Indie Pop'), ('GRUNGE', 'Grunge'), ('SOUL', 'Soul'), ('FUNK', 'Funk'), ('DISCO', 'Disco'), ('GOSPEL', 'Gospel'), ('LATIN', 'Latin'), ('SALSA', 'Salsa'), ('BOSSA_NOVA', 'Bossa Nova'), ('FLAMENCO', 'Flamenco'), ('WORLD', 'World'), ('AFROBEAT', 'Afrobeat'), ('AMBIENT', 'Ambient'), ('LO_FI', 'Lo-Fi'), ('SYNTHWAVE', 'Synthwave'), ('K_POP', 'K-Pop'), ('J_POP', 'J-Pop'), ('BOLLYWOOD', 'Bollywood'), ('CLASSICAL_INDIAN', 'Indian Classical'), ('OPERA', 'Opera'), ('SOUNDTRACK', 'Soundtrack'), ('INSTRUMENTAL', 'Instrumental'), ('ACOUSTIC', 'Acoustic'), ('SINGER_SONGWRITER', 'Singer-Songwriter'), ('EMO', 'Emo'), ('EXPERIMENTAL', 'Experimental'), ('NEW_AGE', 'New Age'), ('CHILDREN', "Children's Music"), ('COMEDY', 'Comedy'), ('CHRISTIAN', 'Christian'), ('HOLIDAY', 'Holiday'), ('TRAP', 'Trap'), ('GRIME', 'Grime'), ('DANCEHALL', 'Dancehall'), ('SWING', 'Swing'), ('BLUEGRASS', 'Bluegrass')], max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('HIP_HOP', 'Hip Hop'), ('RAP', 'Rap'), ('RNB', 'R&B'), ('JAZZ', 'Jazz'), ('BLUES', 'Blues'), ('COUNTRY', 'Country'), ('FOLK', 'Folk'), ('CLASSICAL', 'Classical'), ('ELECTRONIC', 'Electronic'), ('HOUSE', 'House'), ('TECHNO', 'Techno'), ('TRANCE', 'Trance'), ('DUBSTEP', 'Dubstep'), ('DRUM_AND_BASS', 'Drum and Bass'), ('REGGAE', 'Reggae'), ('REGGAETON', 'Reggaeton'), ('SKA', 'Ska'), ('PUNK', 'Punk'), ('METAL', 'Metal'), ('HEAVY_METAL', 'Heavy Metal'), ('DEATH_METAL', 'Death Metal'), ('METALCORE', 'Metalcore'), ('ALTERNATIVE', 'Alternative'), ('INDIE', 'Indie'), ('INDIE_ROCK', 'Indie Rock'), ('INDIE_POP', 'Indie Pop'), ('GRUNGE', 'Grunge'), ('SOUL', 'Soul'), ('FUNK', 'Funk'), ('DISCO', 'Disco'), ('GOSPEL', 'Gospel'), ('LATIN', 'Latin'), ('SALSA', 'Salsa'), ('BOSSA_NOVA', 'Bossa Nova'), ('FLAMENCO', 'Flamenco'), ('WORLD', 'World'), ('AFROBEAT', 'Afrobeat'), ('AMBIENT', 'Ambient'), ('LO_FI', 'Lo-Fi'), ('SYNTHWAVE', 'Synthwave'), ('K_POP', 'K-Pop'), ('J_POP', 'J-Pop'), ('BOLLYWOOD', 'Bollywood'), ('CLASSICAL_INDIAN', 'Indian Classical'), ('OPERA', 'Opera'), ('SOUNDTRACK', 'Soundtrack'), ('INSTRUMENTAL', 'Instrumental'), ('ACOUSTIC', 'Acoustic'), ('SINGER_SONGWRITER', 'Singer-Songwriter'), ('EMO', 'Emo'), ('EXPERIMENTAL', 'Experimental'), ('NEW_AGE', 'New Age'), ('CHILDREN', "Children's Music"), ('COMEDY', 'Comedy'), ('CHRISTIAN', 'Christian'), ('HOLIDAY', 'Holiday'), ('TRAP', 'Trap'), ('GRIME', 'Grime'), ('DANCEHALL', 'Dancehall'), ('SWING', 'Swing'), ('BLUEGRASS', 'Bluegrass')], max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('likes', models.ManyToManyField(related_name='liked_music', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ManyToManyField(related_name='playlists', to='music.music')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='music_recen_user_id_3cb9a4_idx')],
                'unique_together': {('user', 'music')},
            },
        ),
    ]
