# Generated by Django 6.1 on 2026-08-14 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentlyplayed',
            options={'ordering': ['-played_at']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ManyToManyField(related_name='playlists', to='music.music'),
        ),
    ]
