# Generated by Django 6.1 on 2026-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_recentlyplayed_options_alter_artist_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
    ]
